theme: jekyll-theme-architect
name: Endless Space
description: Template Description
author: Mabinogi
author_home: https://github.com/TheMabinogi
location: https://github.com/TheMabinogi/EndlessSpace
custom_wiki: false
custom_release: false
